[package]
name = "parsyng-proc-macros"
description = "Procedural macros used in `parsyng`"
version = "0.1.0"
edition = "2024"
license = "MIT"
readme = "README.md"
repository = "https://github.com/supersurviveur/parsyng"
documentation = "https://docs.rs/parsyng-proc-macros"
rust-version = "1.95"
include = ["/src/**/*.rs", "/Cargo.toml", "/README.md", "/LICENSE"]
keywords = ["macros", "proc", "quote"]
categories = ["development-tools::procedural-macro-helpers"]

[lib]
proc-macro = true

[dependencies]
parsyng-core = { version = "0.1.0", path = "../parsyng-core" }
