[workspace]
resolver = "3"
members = [
  "crates/parsyng-quote-macros",
  "crates/parsyng-proc-macros",
  "crates/parsyng-core",

  "benches/runtime",
  "benches/bench-comptime",
  "benches/bench-quote-comptime",
  "benches/bench-expansion",

  "examples/simple-use",
  "examples/simple-use-macros",
  "examples/heapsize/heapsize",
  "examples/heapsize/heapsize-macros",
  "examples/heapsize/example",
  "examples/debug-attribute/debug-attribute-macros",
  "examples/debug-attribute/example",
]

[package]
name = "parsyng"
description = "A from-scratch, fast-compiling replacement for `syn` + `quote` for writing procedural macros"
version = "0.1.0"
edition = "2024"
license = "MIT"
readme = "README.md"
repository = "https://github.com/supersurviveur/parsyng"
documentation = "https://docs.rs/parsyng"
rust-version = "1.95"
include = ["/src/**/*.rs", "/Cargo.toml", "/README.md", "/LICENSE"]
keywords = ["macros", "proc", "quote"]
categories = ["development-tools::procedural-macro-helpers"]

[dependencies]
parsyng-proc-macros = { version = "0.1.0", path = "./crates/parsyng-proc-macros" }
parsyng-core = { version = "0.1.0", path = "./crates/parsyng-core" }

[features]
proc-macro2 = ["parsyng-core/proc-macro2"]
debug-pretty = ["parsyng-core/debug-pretty"]

