[package]
name = "parsyng-core"
description = "Core components of `parsyng`"
version = "0.1.0"
edition = "2024"
license = "MIT"
readme = "README.md"
repository = "https://github.com/supersurviveur/parsyng"
documentation = "https://docs.rs/parsyng-core"
rust-version = "1.95"
include = ["/src/**/*.rs", "/Cargo.toml", "/README.md", "/LICENSE"]
keywords = ["macros", "proc", "quote"]
categories = ["development-tools::procedural-macro-helpers"]

[dependencies]
parsyng-quote-macros = { version = "0.1.0", path = "../parsyng-quote-macros" }
unicode-ident = "1"

# Optional dependencies
proc-macro2 = { version = "1", optional = true }

[features]
proc-macro2 = ["dep:proc-macro2", "proc-macro2/span-locations"]
debug-pretty = []
