#!/usr/bin/env bash
# Summarises the hyperfine exports (target/bench-results) and criterion
# estimates (target/criterion) into BENCH.md. Run the benches first, e.g. with
# `just bench-report`. Needs `jq`.
set -euo pipefail

root=$(cd "$(dirname "$0")/.." && pwd)
target=${CARGO_TARGET_DIR:-$root/target}
results=$target/bench-results
out=$root/BENCH.md

# Print a hyperfine markdown table with the fastest row (`Relative` = 1.00)
# in bold: its command and mean.
bold_best_row() {
    awk -F'|' -v OFS='|' '
        function trim(s) { gsub(/^ +| +$/, "", s); return s }
        NR > 2 && trim($(NF - 1)) == "1.00" {
            $2 = " **" trim($2) "** "
            $3 = " **" trim($3) "** "
        }
        { print }
    ' "$1"
}

# `## title` + every hyperfine markdown export matching `prefix-*.md`.
hyperfine_section() {
    local title=$1 prefix=$2 description=$3 file name
    echo "## $title"
    echo
    echo "$description"
    echo
    for file in "$results/$prefix"*.md; do
        [[ -e $file ]] || { echo "_Not run._"; echo; return; }
        name=$(basename "$file" .md)
        name=${name#"$prefix"}
        name=${name#-}
        echo "#### ${name:-debug}"
        echo
        bold_best_row "$file"
        echo
    done
}

# One table per kind of criterion group (quote, parse, roundtrip, tokenize):
# a row per case, a column per library, the fastest mean in bold.
criterion_section() {
    echo "## Runtime"
    echo
    echo "Criterion mean ± standard deviation per iteration (\`just bench-runtime\`)."
    echo
    shopt -s nullglob
    local files=("$target"/criterion/*/*/new/benchmark.json)
    if ((${#files[@]} == 0)); then
        echo "_Not run._"
        echo
        return
    fi
    for b in "${files[@]}"; do
        jq -c --slurpfile e "$(dirname "$b")/estimates.json" \
            '{group: .group_id, lib: .function_id, mean: $e[0].mean.point_estimate, sd: $e[0].std_dev.point_estimate}' "$b"
    done | jq -s -r '
        def fmt: if . >= 1e6 then "\(. / 1e6 * 100 | round / 100) ms"
                 elif . >= 1e3 then "\(. / 1e3 * 100 | round / 100) µs"
                 else "\(. * 100 | round / 100) ns" end;
        def rank: . as $l | ["quote", "syn", "proc-macro2", "parsyng", "unsynn", "moxy"] | index($l) // 99;
        group_by(.group | split("/")[0])[]
        | (.[0].group | split("/")[0]) as $kind
        | ([.[].lib] | unique | sort_by(rank)) as $libs
        | "### \($kind)\n",
          "| case | " + ($libs | join(" | ")) + " |",
          "|---|" + ($libs | map("---:") | join("|")) + "|",
          (group_by(.group)[]
           | . as $rows
           | (map(.mean) | min) as $best
           | "| \(.[0].group | split("/")[1:] | join("/")) | "
             + ($libs | map(. as $l | ([$rows[] | select(.lib == $l)] | first) as $r
                 | if $r == null then "n/a"
                   elif $r.mean == $best then "**\($r.mean | fmt)** ± \($r.sd | fmt)"
                   else "\($r.mean | fmt) ± \($r.sd | fmt)" end)
               | join(" | "))
             + " |"),
          ""'
}

# Versions of the libraries the benches actually depend on.
versions() {
    cargo tree -q --manifest-path "$root/Cargo.toml" -p parsyng-bench-runtime --depth 1 -e normal,dev --prefix none 2>/dev/null |
        grep -E '^(syn|quote|proc-macro2|unsynn|moxy|criterion) ' | sort -u | paste -sd, - | sed 's/,/, /g'
}

cpu=$(grep -m1 'model name' /proc/cpuinfo 2>/dev/null | cut -d: -f2 | sed 's/^ //' || true)

{
    cat <<MD
# Benchmarks

parsyng compared with syn + quote, unsynn and moxy. This file is generated by
\`just bench-report\` (\`benches/report.sh\`); see \`benches/\` for the sources.

- Date: $(date -u +%Y-%m-%d)
- Machine: $(uname -sm)${cpu:+, $cpu}
- Toolchain: $(rustc -V)
- Versions: $(versions)

MD
    hyperfine_section "Compile time: library" "comptime" \
        "Clean build of a proc-macro crate (\`benches/bench-comptime\`) implementing the same derive with each library, dependencies included. \`empty\`: the library is only a dependency; \`small\`: parse a struct and emit a one-line impl; \`big\`: a heapsize-style derive with generics handling and per-field repetition; \`big-fallback\`: same, with parsyng built on its pure-Rust \`fallback\` tokens."
    hyperfine_section "Compile time: quote! only" "quote-comptime" \
        "Clean build of a proc-macro crate (\`benches/bench-quote-comptime\`) expanding the same template with each library's quasi-quoting macro."
    hyperfine_section "Compile time: macro expansion" "expansion" \
        "Build of \`benches/bench-expansion\`, 200 \`#[derive(HeapSize)]\` structs, with the derive macro already built: measures expansion plus compiling the output. \`parse\`: build of \`benches/bench-parse\`, whose \`parse_bench!\` parses ~75 KB of real-world Rust (the tokio common subset) and emits nothing: parsing speed on the compiler's real \`proc_macro\`."
    criterion_section
    cat <<'MD'
## Caveats

- **unsynn** ships no Rust grammar. Its derives and the `parse/derive_input`
  case use a minimal hand-written grammar (`benches/runtime/src/lib.rs`,
  `benches/bench-comptime/src/unsynn_impl.rs`) that recognises only what the
  fixtures need, so it does much less work than a full `DeriveInput` parser.
  It takes no part in whole-file parsing.
- **moxy** 0.5 cannot parse `crate::`/`super::`/`self::` paths, so it fails on
  every whole real-world file (`parse/file/*` shows `n/a`). It also silently
  drops some statements. `parse/common/*` and `roundtrip/*` therefore run all
  three full parsers on the top-level items moxy round-trips faithfully.
- **tokenize** compares lexers only: syn and unsynn lex with proc-macro2,
  parsyng with its `fallback` tokens, moxy with its own lexer.
- Runtime numbers use `proc_macro2` for syn, quote and unsynn, and parsyng's
  `fallback` tokens for parsyng; inside a real proc macro they would all use
  the compiler's `proc_macro`.
MD
} >"$out"

echo "Wrote $out"
